### ISSUE TITLE
API definitions

### ISSUE THREAD

**Issue by januswel** [builderscon/nanp#7]
How about using JSON schema?

**Comment by lestrrat** [comment]
よいのでは！

**Comment by dictav** [comment]
JSON hyper-schema 対応のJSクライアントがなさそうなのが気になってます。
swagger には swagger-client があり、redux との連携も難しくなさそうでした。

redux-swagger-client
https://www.npmjs.com/package/redux-swagger-client
https://github.com/noh4ck/redux-swagger-client/blob/master/lib/index.js

**Comment by lestrrat** [comment]
ないのw swaggerにするならoctavもswaggerにしないとかなぁ…

**Comment by dictav** [comment]
https://www.npmjs.com/package/hyper-api-client
こういうのはあるんですが、weekly DL が１桁とか。
json-schema.org で紹介されている jsonary も全くアクティブではなくて、何を使って良いのか分からない感じです。

ただ、昨年10月くらいから JSON-schema がまた活発に動き始めていて、どっちが良いのでしょうね...
https://github.com/json-schema-org/json-schema-spec/graphs/contributors

**Comment by januswel** [comment]
ぐむむ
考えないとダメですね…

**Comment by lestrrat** [comment]
なんか必要そうなAPIの一覧（別に最終バージョンでなくていい）って出ますかね？あったら手の空いている時に考えます

**Comment by januswel** [comment]
OAuth で認証

- Facebook
- Twitter
- Github

**Comment by januswel** [comment]
builderscon/octav の実装をみればよい

**Comment by dictav** [comment]
メモ

[redux-swagger-client](https://www.npmjs.com/package/redux-swagger-client) を使うために JSON hyper-schema => swagger のコンバートを考えてみましたが、簡単ではなかったので諦めました。

そもそも２つくらいしかAPIに触らないので、コンバートに労力をかけるのではなく、api.json を取り込むのをやめて、client を独自に実装する方向で話が進みました

**Comment by januswel** [comment]
というわけなのでこの issue とじますー
